### ISSUE TITLE
Inconsistent path separators

### ISSUE THREAD

**Issue by mamrt** [philip-sorokin/word-template-engine#1]
Consider using DIRECTORY_SEPARATOR constant instead of hardcoding '/' path separator. It causes issues on Windows platform, especially in save() method. Works great otherwise, thank you.

**Comment by philip-sorokin** [comment]
Hello, @mamrt!

Thank you for your feedback. Please, test a new pre-release 1.0.2, where I fixed this issue: https://github.com/philip-sorokin/word-template-engine/releases

Please, let me know, if it works.

**Comment by mamrt** [comment]
ok except an error condition in save() method line 1014; should be:
`  if (mb_strpos($destination, '/') == 0 && mb_strpos($destination, '\\') == 0)`
instead of
`  if (mb_strpos($destination, '/') !== 0 && mb_strpos($destination, '\\') !== 0)`

Another issue comes to my mind - when deploying on a multiuser site there could be a conflict in the temp directory `"temp_wte"`. Generating a unique subdirectory name would resolve this issue.

**Comment by philip-sorokin** [comment]
@mamrt 1014 line is OK. If it does not begin with `/` or `\`, it is a relative path, and the temp dir is prepended to the path. I forgot that Windows paths start with a disk name, like `C:\`.

So, it must be:

`if (mb_strpos($destination, '/') !== 0 && mb_strpos($destination, '\\') !== 0 && mb_strpos($destination, ':') === false)`

Please, check this again.

Regarding multiuser issues. Please, correct me, I thought PHP does not support multithreading, and executes scripts in a single sequence in a queue. Do you think it can potentially cause issues? What do you think?

Thank you for your help!

**Comment by mamrt** [comment]
I suppose you are checking on line 1014 whether $destination is a bare filename and needs to be prepended with $tmpDir; then it must not contain any of '/' '\\' ':' - this is correct:
`if (mb_strpos($destination, '/') === false && mb_strpos($destination, '\\') === false && mb_strpos($destination, ':') === false)`

In my configuration PHP is run via fcgid and there are dozens of simultaneous processes when busy, each of which can be accessing the temp dir at the same time, overwriting or deleting someone else's files.

**Comment by philip-sorokin** [comment]
@mamrt I made a new pre-release with unique tmp subdirectories and also changed line 1014. Please, check it!

**Comment by mamrt** [comment]
Temp dir: perfect, exactly what I was thinking of;

Save method: well... after a second look I changed my mind. Why do you need to modify this parameter at all? If I say I want the file to be saved somewhere, you are not supposed to change it. Now it works as follows:
`save(fullpath/filename)` - ok, file is where I want it to be
`save(filename_only)` - wrong - file is saved in a temp dir and is deleted with it after the object is destroyed - definitely not what I expect - I expect it to be in the current working directory. You can drop the lines 1013-1016 completely.

Anyway, it is now exactly what I was looking for, ready to be deplyed in a multiuser environment. Thank you.

**Comment by philip-sorokin** [comment]
@mamrt, thank you for your help. I edited the class again to add a more safe `random_int` way to generate a random hash for temporary directory. 

Inner functions call `save` method to create temporary files, that are removed in the destructor. Let it be this way. If you need to use the current directory, just don't override the temp dir in the constructor. By default, tmp is the site root / current directory (mostly, the same). I published a new release 1.0.2.

Closing this issue. Do not hesitate to contact if you have any problems.
