### ISSUE TITLE
How To Use?

### ISSUE THREAD

**Issue by cyberzilla** [philip-sorokin/word-template-engine#2]
`<?php
// Require the library
require_once 'WordTemplateEngine.php';

// Require the WordTemplateEngineExamples class with examples if you need
require_once 'examples/examples.php';

$doc = 'template.docx';

/* Example 1. */
$template = new WordTemplateEngine($doc);

/* Example 2. Define temporary directory */
$template = new WordTemplateEngine($doc, 'tmp');

/* Example 3. Attach custom error handler */
$template = new WordTemplateEngine($doc, null, 'myErrorHandler');

$varName = 'company_name';
$replacement = 'AddonDev';

$template->setValue($varName, $replacement);

$varName = 'product_number';
$template->cloneRow($varName, 3);

/* Then replace the variables */

$template->setValue('product_number#1', 1);
$template->setValue('product_number#2', 2);
$template->setValue('product_number#3', 3);

$template->save('newdoc.docx');`

How to use? is there a simple example to make it work? Thanks

**Comment by philip-sorokin** [comment]
Hello! Of course. Please, see the example folder. Require example class and use.

**Comment by cyberzilla** [comment]
> Hello! Of course. Please, see the example folder. Require example class and use.

is my code above is correct?

i got error like this

Fatal error: Uncaught TypeError: Argument 3 passed to WordTemplateEngine::__construct() must be callable or null, string given, called in C:\laragon\www\labs\templating\test.php on line 18 and defined in C:\laragon\www\labs\templating\WordTemplateEngine.php:212 Stack trace: #0 C:\laragon\www\labs\templating\test.php(18): WordTemplateEngine->__construct('template.docx', NULL, 'myErrorHandler') #1 {main} thrown in C:\laragon\www\labs\templating\WordTemplateEngine.php on line 212

**Comment by philip-sorokin** [comment]
Use the first example.

**Comment by cyberzilla** [comment]
> Use the first example.

where is the example?

**Comment by philip-sorokin** [comment]
Here is the example: https://github.com/philip-sorokin/word-template-engine/blob/main/examples/examples.php

**Comment by cyberzilla** [comment]
how to use this example? sorry I'm still a beginner

**Comment by philip-sorokin** [comment]
It's required some php knowledge to understand the code. Also, you can refer to the manual here: https://addondev.com/opensource/word-template-engine

**Comment by cyberzilla** [comment]
is it possible to use only WordTemplateEngine.php without using example.php?

**Comment by cyberzilla** [comment]
Oke, Finally i get the result "newdoc.docx", just like this

```
require_once 'WordTemplateEngine.php';
$template = new WordTemplateEngine("company.docx", 'tmp');
$template->setValue("company_name", "Cyberzilla");
$template->setValue("author", "Abu Dzakiyyah");
$template->replaceImage(2, 'logo.png');
$template->save('../../newdoc.docx');
```

but the image in the template is not replaced, how to find ID of image inside the template? thanks

**Comment by cyberzilla** [comment]
even though I use examples.php to save the result, still the image is not changed

```
$test = new WordTemplateEngineExamples();
$test->replaceSignature();
```

**Comment by philip-sorokin** [comment]
This is a word enumerator. Try different image numbers. I cannot know which exactly this image is.
